---
title: "gp_nkamat"
output:
  html_document: default
  pdf_document: default
---


```{r}
library(lpSolveAPI)
# Demonstrate IP Branch-and-Bound
sp1 <- make.lp(0, 2) # number of constraints, number of decision variables
#Defaults to Minimize objective function
set.objfn(sp1, c(-8, -5))
add.constraint(sp1, c(1, 1), "<=", 6)
add.constraint(sp1, c(9, 5), "<=", 45)
RowNames <- c("y1", "y2")
ColNames <- c("x1", "x2")
dimnames(sp1) <- list(RowNames, ColNames)
sp1

```

```{r}
# Alternatively, write your model in lp format
write.lp(sp1,'ip_nkamat.lp',type='lp') 
solve(sp1)
get.objective(sp1) * -1
get.variables(sp1)
plot(sp1)
```
```{r}
# Now, we have a choice. We will consider values for x1 <=3 (subproblem 3), and x1 >= 4 (sp 2)

# Subproblem 2 = SP1 +  x1 >= 4
sp2 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp2, c(-8, -5))
add.constraint(sp2, c(1, 1), "<=", 6)
add.constraint(sp2, c(9, 5), "<=", 45)
add.constraint(sp2,c(1,0),">=",4)
solve(sp2)
get.objective(sp2) * -1
get.variables(sp2)
plot(sp2)

```
```{r}
# SP 4 = SP 2 + x2 >= 2
sp4 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp4, c(-8, -5))
add.constraint(sp4, c(1, 1), "<=", 6)
add.constraint(sp4, c(9, 5), "<=", 45)
add.constraint(sp4,c(1,0),">=",4)
add.constraint(sp4,c(0,1),">=",2)
solve(sp4)
get.objective(sp4) * -1 # This solution is infeasible
get.variables(sp4)
plot(sp4)

```
```{r}
# SP 5 = SP 2 + x2 <= 1
sp5 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp5, c(-8, -5))
add.constraint(sp5, c(1, 1), "<=", 6)
add.constraint(sp5, c(9, 5), "<=", 45)
add.constraint(sp5,c(1,0),">=",4)
add.constraint(sp5,c(0,1),"<=",1)
solve(sp5)
get.objective(sp5) * -1 
get.variables(sp5)
plot(sp5)
```
```{r}
# SP 6 = SP 5 + x1 >= 5
sp6 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp6, c(-8, -5))
add.constraint(sp6, c(1, 1), "<=", 6)
add.constraint(sp6, c(9, 5), "<=", 45)
add.constraint(sp6,c(1,0),">=",5)
add.constraint(sp6,c(0,1),"<=",1)
solve(sp6)
get.objective(sp6) * -1 
get.variables(sp6) # This is a feasible solution
plot(sp6)
```
```{r}
# SP 7 = SP 5 + x1 <= 4
sp7 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp7, c(-8, -5))
add.constraint(sp7, c(1, 1), "<=", 6)
add.constraint(sp7, c(9, 5), "<=", 45)
add.constraint(sp7,c(1,0),"=",4)
add.constraint(sp7,c(0,1),"<=",1)
solve(sp7)
get.objective(sp7) * -1 
get.variables(sp7) # This is also feasbile, but lower than SP6
plot(sp7)
```

```{r}
# Our best solution is so far SP6 with objective of 40.
# Now, we explore the other branch, SP 3

# Subproblem 3 = SP1 +  x1 <= 3
sp3 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp3, c(-8, -5))
add.constraint(sp3, c(1, 1), "<=", 6)
add.constraint(sp3, c(9, 5), "<=", 45)
add.constraint(sp3,c(1,0),"<=",3)
solve(sp3)
get.objective(sp3) * -1
get.variables(sp3)
plot(sp3)
# The solution to SP3 gives an objective of 39 < SP6 of 40. Further, you will not get a better IP solution from SP3 branch. Hence our optimal solution is SP6.
```
```{r}
# Subproblem 8 = SP1 +  x2 <= 2
sp8 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp8, c(-8, -5))
add.constraint(sp8, c(1, 1), "<=", 6)
add.constraint(sp8, c(9, 5), "<=", 45)
add.constraint(sp8,c(0,1),"<=",2)
solve(sp8)
get.objective(sp8) * -1
get.variables(sp8)
plot(sp8)
```
```{r}
# Subproblem 9 = SP8 +  x1 <= 3
sp9 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp9, c(-8, -5))
add.constraint(sp9, c(1, 1), "<=", 6)
add.constraint(sp9, c(9, 5), "<=", 45)
add.constraint(sp9,c(0,1),"<=",2)
add.constraint(sp9,c(1,0),"<=",3)
solve(sp9)
get.objective(sp9) * -1
get.variables(sp9)
plot(sp9)
# The solution to SP9 gives an objective of 34 < SP6 of 40. Further, you will not get a better IP solution from SP3 branch. Hence our optimal solution is SP6.
```
```{r}
# Subproblem 10 = SP8 +  x1 >= 4
sp10 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp10, c(-8, -5))
add.constraint(sp10, c(1, 1), "<=", 6)
add.constraint(sp10, c(9, 5), "<=", 45)
add.constraint(sp10,c(0,1),"<=",2)
add.constraint(sp10,c(1,0),">=",4)
solve(sp10)
get.objective(sp10) * -1 # This solution is infeasible
get.variables(sp10)
plot(sp10)
```

```{r}
# Subproblem 11 = SP1 +  x2 >= 3
sp11 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp11, c(-8, -5))
add.constraint(sp11, c(1, 1), "<=", 6)
add.constraint(sp11, c(9, 5), "<=", 45)
add.constraint(sp11,c(0,1),">=",3)
solve(sp11)
get.objective(sp11) * -1
get.variables(sp11)
plot(sp11)
# The solution to SP11 gives an objective of 39 < SP6 of 40. Further, you will not get a better IP solution from SP3 branch. Hence our optimal solution is SP6.
```

```{r}
t1<- c(-get.objective(sp1), get.variables(sp1))
t2<- c(-get.objective(sp2), get.variables(sp2))
t3<- c(-get.objective(sp3), get.variables(sp3))
t4<- c(-get.objective(sp4), get.variables(sp4))
t5<- c(-get.objective(sp5), get.variables(sp5)) 
t6<- c(-get.objective(sp6), get.variables(sp6)) #Optimum feasible Solution
t7<- c(-get.objective(sp7), get.variables(sp7))
t8<- c(-get.objective(sp8), get.variables(sp8))
t9<- c(-get.objective(sp9), get.variables(sp9))
t10<- c(-get.objective(sp10), get.variables(sp10))
t11<- c(-get.objective(sp11), get.variables(sp11))
p<- c("solution", "x1", "x2") 
p # feasible solution has x1 and x2 as integers
t1
t2
t3
t4
t5
t6
t7
t8
t9
t10
t11
```

```{r}
library(ggplot2)
library(esquisse)
library(shiny)
p <- read.csv("ip_nkamat.csv")
# data values for x1 and x2
ggplot(data = p) +
  aes(x = x1, y = x2) +
  geom_point(color = "#0c4c8a") +
  theme_minimal()
```

```{r}
library(ggplot2)
library(esquisse)
library(shiny)
p <- read.csv("ip_nkamat.csv")
# Objective function with respect to x1
ggplot(data = p) +
  aes(x = x1, y = Objective) +
  geom_point(color = "#0c4c8a") +
  theme_minimal()
```
```{r}
# Objective function with respect to x2
ggplot(data = p) +
  aes(x = x2, y = Objective) +
  geom_point(color = "#0c4c8a") +
  theme_minimal()
```

